services:
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    networks:
      - db
    ports:
      - "5332:5432"
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:
